### ISSUE TITLE
Asustor change the Way Let's entcrypt work

### ISSUE THREAD

**Issue by nevyen** [bebo-dot-dev/asustor-certbot#1]
Hey, 
thanks for publishing this scripts. 

Since you created them, Asustor changed the way Let's encrypt worked. 

Does this still works on Asustor? 

If I try to create a certificate I get the following error: 

```
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for wg.warzoknet.de
Cleaning up challenges
Problem binding to port 80: Could not bind to IPv4 or IPv6.

```
In my opinion this is because the webserver is running. 

Can you specify how to change the ports of standalone? I searched the web but I can't find any working solution. 

Thanks in advance

**Comment by bebo-dot-dev** [comment]
Hi there,

Yep this still works and is in use here on my AS202-TE. Asustor might have changed something with their support for LetsEncrypt but that doesn't matter at all because using certbot directly bypasses and ignores anything that Asustor have in place for supporting LetsEncrypt TLS certificates because certbot communicates directly with the LetsEncrypt CA.

The docs for certbot are here: https://certbot.eff.org/docs/ and the certbot command for generating a LetsEncrypt TLS certificate using certbot in standalone mode looks like this:

1. `$ /path/to/certbot-directory/certbot certonly --standalone --preferred-challenges http -d <your domain here>` **OR**
2. `$ /path/to/certbot-directory/certbot certonly --standalone --preferred-challenges tls-sni -d <your domain here>`

Example (1) above will cause certbot to spin up a temporal webserver on port 80 to listen for the inbound CA handshake and example (2) above causes certbot to spin up a temporal webserver on port 443 to listen for the inbound CA handshake

Make sure that port 80 / 443 are usable on your NAS box when you attempt this (stop webserver or whatever services are using these ports) and of course before you attempt any of this you need to get certbot installed / built / working on your NAS box.

**Comment by nevyen** [comment]
Hey thanks for your really quick reply. 

As I understand your skripts I than need to forward port 51080 to my NAS for renew the script. Am I right? 

I try to stop the webserver. And get a new certificate. Could it be a problem that I am using a dyndns service?

**Comment by bebo-dot-dev** [comment]
Hi again, I think you're looking at this:

https://github.com/jjssoftware/asustor-certbot/blob/master/nas-certbot-renewal.sh#L21

There are a few things to say about this certbot renewal command:

1. This command assumes that certbot is located / installed in the `/usr/local/AppCentral/python/bin/` directory. 
2. If you leave this shell script as-is and execute it on your NAS box it will cause certbot to perform a renewal attempt using the configuration in the directory specified by the `--config-dir` argument. You should check that this argument specifies the correct location on your NAS where letsencrypt and config files reside. 
3. When certbot runs the renewal, specifying `--preferred-challenges=http` describes that the CA callback should be performed via http and specifying `--http-01-port 51080` describes that the CA http callback should be performed on port 51080.
4. It's also worthwhile mentioning that this http challenge certbot renewal command causes certbot to spin up a temporary webserver on port 80 for the short period of time when a certificate renewal actually occurs. This means that you'll either need to ensure that port 80 is never used and is always free for certbot to use or you'll need to stop and restart whatever service uses port 80 at certificate renewal time (if necessary, automation of this stop/start operation is doable in a shell script too).

With all this said, if you were to use a certbot renewal command similar to the one in the sample .sh script, you would need to forward port 51080 to port 80 on your NAS to enable the Letsencrypt CA http renewal callback to work all the way through to certbot. You don't really have to use port 51080, it's just slightly better than having port 80 permanently forwarded / open. In addition if you don't want to, you're not forced to use a http challenge at all with certbot - take a look at the certbot docs and see that there are other ways to complete a challenge (i.e. DNS record). Hope that helps.

**Comment by nevyen** [comment]
Thanks for your really usefull help. 

I will try to get it work at the next week. 

Maybe I will than post a manual here ;-) 

Thanks for sharing this option.

**Comment by bebo-dot-dev** [comment]
No problem. The most difficult part of getting this working I found was getting certbot installed and built due to Asustor's special Linux build having limited compile and build tools easily available and installable. That was some time ago on my AS202TE though and things might be better and easier nowadays. Once certbot is working on the NAS box it's plain sailing. Good luck.
